CREATE TABLE IF NOT EXISTS
    PRODUCTS
        (
            PRODUCT_CODE VARCHAR(8) PRIMARY KEY,
            PRODUCT_NAME VARCHAR(100)
        );

CREATE TABLE IF NOT EXISTS
    PRODUCT_VARIANTS
        (
            PRODUCT_CODE VARCHAR(8),
            VARIANT_CODE VARCHAR(2),
            COLOR_CODE VARCHAR(2),
            PRICE INT,
            RELEASE_DATE VARCHAR(8),
            PRIMARY KEY(PRODUCT_CODE,VARIANT_CODE)
        );

CREATE TABLE IF NOT EXISTS
    PRODUCT_IMAGE
        (
            PRODUCT_CODE VARCHAR(8),
            VARIANT_CODE VARCHAR(2),
            PRIORITY_NUMBER INT,
            THUMBNAIL_FLAG VARCHAR(1),
            IMAGE_URL TEXT,
            PRIMARY KEY(PRODUCT_CODE,VARIANT_CODE,PRIORITY_NUMBER)
        );

CREATE TABLE IF NOT EXISTS
    PURCHASE_HISTORY
        (
            PURCHASE_NUMBER INT PRIMARY KEY,
            PURCHASE_DATETIME VARCHAR(14),
            PRODUCT_CODE VARCHAR(8),
            VARIANT_CODE VARCHAR(2),
            QUANTITY INT
        );
